version: "3.8"

services: 
  chrome:
    image: selenium/node-chrome:4.1.0
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    depends_on:
      - selenium-hub
    networks:
      - selenium-grid